# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('age', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_share_view', models.CharField(max_length=5)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.User')),
                ('last_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Account')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.User'),
        ),
        migrations.AddField(
            model_name='account',
            name='entity_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Entity'),
        ),
    ]
